DROP DATABASE ecommerceLiliENana;
CREATE DATABASE ecommerceLiliENana;

use ecommerceLiliENana;


CREATE TABLE EMPRESA(
	CNPJ VARCHAR(14) NOT NULL UNIQUE,
    Nome VARCHAR(30) NOT NULL,
    PRIMARY KEY(CNPJ)
);

CREATE TABLE CATEGORIA(
	idCategoria INT NOT NULL AUTO_INCREMENT,
	NomeCategoria VARCHAR(20) NOT NULL,
    PRIMARY KEY(idCategoria)
);

CREATE TABLE PESSOA(
	CPF VARCHAR(14) UNIQUE,
    NOME VARCHAR(50) NOT NULL,
    SEXO char NOT NULL CHECK (sexo IN ('F', 'M')),
    Telefone VARCHAR(14),
    EMAIL VARCHAR(50) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    RUA VARCHAR(50) NOT NULL ,
    CIDADE VARCHAR(25) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL CHECK (Estado IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    REFERENCIA VARCHAR(70),
    PRIMARY KEY(CPF)
);

CREATE TABLE FORNECEDOR(
	CNPJ VARCHAR(14) NOT NULL,
    NOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    CEP VARCHAR(9) NOT NULL,
    RUA VARCHAR(50) NOT NULL ,
    CIDADE VARCHAR(25) NOT NULL,
    NUMERO VARCHAR(6) NOT NULL,
    ESTADO VARCHAR(2) NOT NULL CHECK (Estado IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    REFERENCIA VARCHAR(70),
    PRIMARY KEY(CNPJ)
    
);

CREATE TABLE CLIENTE(
	cpfCliente VARCHAR(14),
    classeCliente VARCHAR(16) NOT NULL CHECK (classeCliente IN ('Básico', 'VIP', 'VIP+')), 
    
    PRIMARY KEY(cpfCliente),
    FOREIGN KEY(cpfCLiente) REFERENCES PESSOA(CPF) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FUNCIONARIO (
    CPFfuncionario VARCHAR(14) UNIQUE NOT NULL,
    CPFGerente VARCHAR(14),
    CNPJ VARCHAR(14) NOT NULL,
    idDpto INT,
    NumeroConta VARCHAR(20) NOT NULL,
    AgenciaConta VARCHAR(10) NOT NULL,
    PRIMARY KEY(CPFfuncionario)
    
);

#CRIAR PRIMEIRO FUNCIONARIO, DEPOIS CRIAR A TABELA DEPARTAMENTO, LOGO EM SEGUIDA OS ALTER TABLES PARA ADICIONAR CONSTRAINT

CREATE TABLE DEPARTAMENTO(
	idDpto INT AUTO_INCREMENT,
    CPFGerente VARCHAR(14),
    nomeDpto VARCHAR(100) UNIQUE NOT NULL,
    PRIMARY KEY(idDpto),
    FOREIGN KEY(CPFGerente) references FUNCIONARIO(CPFfuncionario) ON DELETE SET NULL ON UPDATE CASCADE

);


ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK1FUNC FOREIGN KEY (CPFfuncionario) REFERENCES PESSOA(CPF) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK2FUNC FOREIGN KEY (CpfGerente) REFERENCES FUNCIONARIO(CPFfuncionario) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK3FUNC FOREIGN KEY (CNPJ) REFERENCES EMPRESA(CNPJ)ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK4FUNC FOREIGN KEY (idDpto) REFERENCES DEPARTAMENTO(idDpto) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE PRODUTO(
	idProduto INT AUTO_INCREMENT NOT NULL,
    precoProduto NUMERIC(10,2) NOT NULL,
    quantEstoque INT CHECK (quantEstoque >= 0),
    descProduto VARCHAR(100) NOT NULL,
    idCategoria INT NOT NULL,
    
    PRIMARY KEY (idProduto),
    FOREIGN KEY(idCategoria) REFERENCES CATEGORIA(idCategoria) ON UPDATE CASCADE
);

CREATE TABLE CARRINHO(
	idCarrinho INT AUTO_INCREMENT,
    CPFCliente VARCHAR(14),
    quantProduto INT CHECK (quantProduto > 0),
    
    PRIMARY KEY (idCarrinho),
    FOREIGN KEY(CPFCliente) REFERENCES CLIENTE(cpfCliente) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE COMPRA ( 
	idCompra INT AUTO_INCREMENT,
	idCarrinho INT,
	precoTotal NUMERIC(10,2) CHECK (precoTotal >= 0),
	`status` VARCHAR(20) CHECK (`status` IN ('Entregue', 'Enviado',' Processamento')),
	dataCompra DATE,
    
    PRIMARY KEY(idCompra),
    FOREIGN KEY (idCarrinho) REFERENCES CARRINHO(idCarrinho) ON UPDATE CASCADE

);

CREATE TABLE Item(
	idItem INT NOT NULL,
	idProduto INT NOT NULL,
	idCarrinho INT,
    
    PRIMARY KEY(idItem),
	FOREIGN KEY (idProduto) REFERENCES PRODUTO(idProduto) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (idCarrinho) REFERENCES CARRINHO(idCarrinho) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE NotaFiscal(
	serieNF INT,
    numeroNF INT,
    `status` VARCHAR(30) CHECK(`status` IN ('Emitida','Cancelada','Autorizada')),
    FormaDePagamento VARCHAR(30) CHECK(FormaDePagamento IN ('Pix','Cartão de débito','Cartão de crédito','Boleto')),
    dataEmissao date,
    valorTotalCompra NUMERIC(10,2) CHECK(valorTotalCompra >= 0),
    idCompra INT,
    
    PRIMARY KEY(serieNF,numeroNF),
    FOREIGN KEY(idCompra) REFERENCES COMPRA(idCompra) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FORNECIDO(
	qtdForn INT CHECK (qtdForn > 0) NOT NULL,
    dataEntrega DATE,
    CNPJ VARCHAR(14),
    idProduto INT,
    
    PRIMARY KEY (CNPJ,idProduto),
    FOREIGN KEY (CNPJ) REFERENCES FORNECEDOR(CNPJ) ON DELETE RESTRICT ON UPDATE CASCADE,
    FOREIGN KEY (idProduto) REFERENCES PRODUTO(idProduto) ON DELETE RESTRICT ON UPDATE CASCADE
);
















